name: rups-backend
networks:
  app-network:
    driver: bridge

services:
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    restart: always
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_DB_URL}
      ME_CONFIG_BASICAUTH: false
    networks:
      - app-network
    depends_on:
      - mongo

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_PAT: ${GITHUB_PAT}
        NODE_ENV: ${ENV}
        APP_PORT: ${APP_PORT}
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app/rest-api
      - ./node_modules:/app/rest-api/node_modules
    environment:
      - NODE_ENV=${ENV}
    depends_on:
      - mongo
    networks:
      - app-network
volumes:
  mongo-data:


