networks:
  app-network:
    driver: bridge

services:
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    restart: always
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMIPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_DB_URL}
      ME_CONFIG_BASICAUTH: false
    networks:
      - app-network
    depends_on:
      - mongo

  rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - NODE_ENV=${ENV}
    volumes:
      - .:/app/rest-api
      - /app/rest-api/node_modules
    depends_on:
      - mongo
    networks:
      - app-network
volumes:
  mongo-data:


